targetNamespace: ''
parameters: {}
environment: {}
packages:
  - name: postcard
    environment:
      POSTCARD_FUNCTION_SECRET: '${POSTCARD_FUNCTION_SECRET}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
    functions:
      - name: generate
        runtime: 'nodejs:24'
        main: main
        web: true
        webSecure: '${POSTCARD_FUNCTION_SECRET}'
        limits:
          timeout: 300000
          memory: 512
